name: Question or Help
description: Ask a question about using LocalGearbox
title: '[Question]: '
labels: ['question']
body:
  - type: markdown
    attributes:
      value: |
        Have a question about LocalGearbox? We're here to help!

  - type: dropdown
    id: topic
    attributes:
      label: Question Topic
      description: What is your question about?
      options:
        - Using a specific tool
        - Self-hosting / Deployment
        - Privacy and Security
        - Performance
        - Browser Compatibility
        - Contributing
        - General Usage
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: Please describe your question in detail
      placeholder: I would like to know...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Provide any additional context that might help us answer your question
      placeholder: I'm trying to... / I've already tried...
    validations:
      required: false

  - type: dropdown
    id: docs-checked
    attributes:
      label: Have you checked the documentation?
      description: Have you looked at the README, CONTRIBUTING, or other documentation?
      options:
        - "Yes, but couldn't find the answer"
        - 'No, not yet'
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your question
      placeholder: Drag and drop images here
    validations:
      required: false
